vich_uploader:
    db_driver: orm

    mappings:
        profile_image:
            uri_prefix: /images/profile_image
            upload_destination: '%kernel.project_dir%/public/images/profile_image'
            namer: Vich\UploaderBundle\Naming\UniqidNamer